name: Build and deploy Dockerized app to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      short_sha: ${{ steps.set_output.outputs.short_sha }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - id: set_output
        run: echo "::set-output name=short_sha::$(git rev-parse --short=5 HEAD)"

  build:
    needs: setup
    runs-on: ubuntu-latest
    outputs:
      short_sha: ${{ needs.setup.outputs.short_sha }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get short SHA
        id: set_output
        run: echo "::set-output name=short_sha::$(git rev-parse --short=5 HEAD)"

      # Use the variable in subsequent steps
      - name: Use Short SHA
        run: echo "The short SHA is ${{ needs.setup.outputs.short_sha }}"

      - name: Build and push Docker image
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      
      - name: Build Docker image
        run: docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/psycho-scan-server-container:${{ needs.setup.outputs.short_sha }} .

      - name: Push Docker image
        run: docker push ${{ secrets.ACR_LOGIN_SERVER }}/psycho-scan-server-container:${{ needs.setup.outputs.short_sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
    steps:
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'psycho-scan-app'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: '${{ secrets.ACR_LOGIN_SERVER }}/psycho-scan-server-container:${{ needs.build.outputs.short_sha }}'
